name: Maven

on: 
  push:
    branches:
     - master
     #- dev
  #pull_request:
    #branches:
     #- master
     #- dev

jobs:
  maven:
    name: Units & Integrations
    #runs-on: ubuntu-latest
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        # syntax inspired from https://github.community/t5/GitHub-Actions/Using-a-matrix-defined-input-for-a-custom-action/m-p/32032/highlight/true#M988
        os:
          - {name: macos-latest, short: "macos" }
          - {name: ubuntu-latest, short: "ubuntu" }
          - {name: windows-latest, short: "windows" }

    steps:
     - name: Checkout repo
       uses: actions/checkout@v1

     - name: Set up JDK 1.8
       uses: actions/setup-java@v1
       with:
         java-version: 1.8

     - name: Cache maven build
       uses: actions/cache@v1
       with:
         path: ~/.m2/repository
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: |
            ${{ runner.os }}-maven-

     - name: Compile with Maven
       run: mvn compile

     - name: Verify
       run: mvn verify

     - name: Testing
       run: mvn test
       # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=hbstarjason_springboot-k8s-example
     
     - name: Package
       run: mvn clean package -Dmaven.test.skip=true -s ./settings.xml
  
     - name: Show Error Logs
       if: failure()
       run: |
          cat hs_err_pid*
          rm hs_err_pid*

  
